name: lgf
channels:
  - pytorch
  - conda-forge
dependencies:
  - python>=3.7
  - numpy
  - pytorch==1.3.1
  - torchvision==0.4.2
  - pillow==6.2.1
  - ignite==0.2.1
  - imageio
  - pandas
  - matplotlib
  - scikit-learn
  - tensorboardx
  - tqdm
  - pytest
  - h5py
  - pip
  - pip:
    - pyro-ppl>=1.0
    - git+https://github.com/rtqichen/torchdiffeq
